# Generated by Django 4.2.16 on 2024-10-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('measurement_unit', models.CharField(choices=[('г', 'Грамм'), ('кг', 'Килорамм'), ('л', 'Литр'), ('мл', 'Миллитр'), ('чашка', 'Чашка'), ('чашки', 'Чашки'), ('ложка', 'ложка'), ('ложки', 'ложки')], max_length=64)),
            ],
        ),
    ]
