# Generated by Django 4.2.16 on 2024-10-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_alter_ingredient_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('г', 'Грамм'), ('кг', 'Килорамм'), ('л', 'Литр'), ('мл', 'Миллитр'), ('шт.', 'шт.'), ('банка', 'банка'), ('ст. л.', 'ст. л.'), ('ч. л.', 'ч. л.'), ('капля', 'капля'), ('стакан', 'стакан'), ('щепотка', 'щепотка'), ('батон', 'батон')], max_length=64),
        ),
    ]
