# Generated by Django 4.2.16 on 2024-11-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0004_ingredient_unique_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(choices=[('г', 'Грамм'), ('кг', 'Килорамм'), ('л', 'Литр'), ('мл', 'Миллитр'), ('шт.', 'шт.'), ('банка', 'банка'), ('ст. л.', 'ст. л.'), ('ч. л.', 'ч. л.'), ('капля', 'капля'), ('стакан', 'стакан'), ('щепотка', 'щепотка'), ('батон', 'батон')], max_length=64, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
    ]
