volumes:
  pg_data:
  static:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: vladimirazanza/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media_volume:/app/media
      - ./data:/data
  frontend:
    env_file: .env
    image: vladimirazanza/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: vladimirazanza/foodgram_gateway
    env_file: .env
    ports:
      - 8001:80
    volumes:
      - static:/static
      - media_volume:/app/media