# Generated by Django 4.2.16 on 2024-10-14 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('slug', models.SlugField(help_text='Введите допустимый "слаг", состоящий из латинских букв, букв, цифр, подчеркиваний или дефисов.', max_length=32)),
            ],
        ),
    ]
