# Generated by Django 4.2.16 on 2024-10-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(error_messages='Введите допустимый "слаг", состоящий из латинских букв, букв, цифр, подчеркиваний или дефисов.', help_text='Введите допустимый "слаг", состоящий из латинских букв, букв, цифр, подчеркиваний или дефисов.', max_length=32),
        ),
    ]
