# Generated by Django 4.2.16 on 2024-10-28 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_alter_tag_name_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(error_messages={'invalid': 'Введите действительный slug (латиница, цифры, _ или -).', 'max_length': 'Slug не может превышать {max_length} символов.', 'unique': 'Slug должен быть уникальным.'}, help_text={'invalid': 'Введите действительный slug (латиница, цифры, _ или -).', 'max_length': 'Slug не может превышать {max_length} символов.', 'unique': 'Slug должен быть уникальным.'}, max_length=32, unique=True),
        ),
    ]
