# Generated by Django 4.2.16 on 2024-11-01 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(error_messages={'invalid': 'Введите действительный slug (латиница, цифры, _ или -).', 'max_length': 'Slug не может превышать {max_length} символов.', 'unique': 'Slug должен быть уникальным.'}, help_text='Slug не может превышать 32 символов.Slug должен быть уникальным.Введите действительный slug (латиница, цифры, _ или -).', max_length=32, unique=True, verbose_name='Слаг'),
        ),
    ]
