# Generated by Django 4.2.16 on 2024-11-05 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0006_alter_tag_name_alter_tag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(error_messages={'invalid': 'Введите действительный слаг (латиница, цифры, _ или -).', 'max_length': 'Слаг не может превышать 32 символов.', 'unique': 'Слаг должен быть уникальным.'}, help_text='Слаг не может превышать 32 символов. Слаг должен быть уникальным. Введите действительный слаг (латиница, цифры, _ или -).', max_length=32, unique=True, verbose_name='Слаг'),
        ),
    ]
