# Generated by Django 4.2.16 on 2024-11-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_ingredientrecipe_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default='recipes/placeholder.png', upload_to='recipes/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
