# Generated by Django 4.2.16 on 2024-10-22 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_suscription_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Suscription',
            new_name='Subscription',
        ),
    ]
