# Generated by Django 4.2.16 on 2024-11-06 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_subscription_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
